# Generated by Django 4.2.5 on 2025-11-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_completion_time', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('abandonment_rate', models.FloatField(default=0.0)),
                ('average_time_spent', models.FloatField(default=0.0)),
                ('form_analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_analytics', to='analytics.formanalytics')),
            ],
            options={
                'indexes': [models.Index(fields=['form_analytics', 'field_id'], name='analytics_f_form_an_593f1d_idx'), models.Index(fields=['field_type'], name='analytics_f_field_t_cc8ddd_idx')],
                'unique_together': {('form_analytics', 'field_id')},
            },
        ),
    ]
