# Generated by Django 4.2.5 on 2025-11-05 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form', 'created_at'], name='submissions_form_id_6e1993_idx'), models.Index(fields=['form', '-created_at'], name='submissions_form_id_df8c6a_idx'), models.Index(fields=['ip_address'], name='submissions_ip_addr_200f97_idx'), models.Index(fields=['is_spam'], name='submissions_is_spam_fafb4e_idx'), models.Index(fields=['-created_at'], name='submissions_created_be6fdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('session_key', models.CharField(max_length=40)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_forms', to='forms.form')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key'], name='submissions_session_3641b3_idx')],
                'unique_together': {('form', 'session_key')},
            },
        ),
    ]
